timetracker/entries/urls.py
from django.conf.urls import url

from . import views


urlpatterns = [
    url(r'^clients/$', views.clients, name='client-list'),
    url(r'^clients/(?P<pk>\d+)/$', views.client_detail, name='client-detail'),
    url(r'^entries/$', views.entries, name='entry-list'),
    url(r'^projects/$', views.projects, name='project-list'),
]

timetracker/timetracker/urls.py
from django.conf.urls import include, url
from django.contrib import admin

from entries import urls as entry_urls


urlpatterns = [
    url(r'^', include(entry_urls)),
    url(r'^admin/', include(admin.site.urls)),
]

timetracker/entries/models.py
from django.db import models
from django.utils import timezone


class Client(models.Model):
    name = models.CharField(max_length=200)

    def __str__(self):
        return self.name


class Project(models.Model):
    client = models.ForeignKey('Client', blank=True, null=True)
    name = models.CharField(max_length=200)

    def __str__(self):
        return '<{}> {}'.format(self.client, self.name)


# Create your models here.
class Entry(models.Model):
    start = models.DateTimeField(default=timezone.now)
    stop = models.DateTimeField(blank=True, null=True)
    project = models.ForeignKey('Project')
    description = models.CharField(max_length=200)

    class Meta:
        verbose_name_plural = 'entries'

    def __str__(self):
        return '[{} - {}] ({}) {}'.format(self.start, self.stop, self.project.name, self.description)

    def is_finished(self):
        return self.stop is not None

timetracker/entries/forms.py
from django.core.exceptions import ValidationError
from django.utils import timezone
from django import forms

from .models import Project
from .models import Client


class ClientForm(forms.Form):
    name = forms.CharField()

class ProjectForm(forms.Form):
    name = forms.CharField()
    client = forms.ModelChoiceField(queryset=Client.objects.all())

class EntryForm(forms.Form):
    start = forms.DateTimeField(label="Start Time", help_text="Format: 2006-10-25 14:30")
    end = forms.DateTimeField(label="End Time", help_text="Format: 2006-10-25 14:30")
    project = forms.ModelChoiceField(queryset=Project.objects.all())
    description = forms.CharField()

    def clean(self):
        start = self.cleaned_data.get('start')
        end = self.cleaned_data.get('end')

        if start > timezone.now():
            raise ValidationError("Start time must be in the past")

        if start > end:
            raise ValidationError("You can't finish something before you've started it")

        return self.cleaned_data

timetracker/entries/views.py
from django.shortcuts import render, get_object_or_404

from .forms import EntryForm
from .forms import ProjectForm
from .forms import ClientForm
from .models import Client, Entry, Project


def clients(request):
    if request.method == 'POST':
        client_form = ClientForm(request.POST)
        if client_form.is_valid():
            client = Client()
            client.name = client_form.cleaned_data['name']
            client.save()
    else:
        client_form = ClientForm()

    client_list = Client.objects.all()
    return render(request, 'clients.html', {
        'client_list': client_list,
        'client_form': client_form
    })


def client_detail(request, pk):
    client = get_object_or_404(Client, pk=pk)
    return render(request, 'client_detail.html', {
        'client': client,
    })


def entries(request):
    if request.method == 'POST':
        # Create our form object with our POST data
        entry_form = EntryForm(request.POST)
        if entry_form.is_valid():
            # If the form is valid, let's create and Entry with the submitted data
            entry = Entry()
            entry.start = entry_form.cleaned_data['start']
            entry.end = entry_form.cleaned_data['end']
            entry.project = entry_form.cleaned_data['project']
            entry.description = entry_form.cleaned_data['description']
            entry.save()
    else:
        entry_form = EntryForm()

    entry_list = Entry.objects.all()
    return render(request, 'entries.html', {
        'entry_list': entry_list,
        'entry_form': entry_form,
    })

def projects(request):
    if request.method == 'POST':
        project_form = ProjectForm(request.POST)
        if project_form.is_valid():
            project = Project()
            project.name = project_form.cleaned_data['name']
            project.client = project_form.cleaned_data['client']
            project.save()
    else:
        project_form = ProjectForm()

    project_list = Project.objects.all()
    return render(request, 'projects.html', {
        'project_list': project_list,
        'project_form': project_form,
    })

timetracker/entries/templates/base.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>{% block title %}TimeTracker{% endblock %}</title>

    <style media="screen">
      .container {
        width: 40em;
        margin: 0 auto;
        font-family: 'Helvetica', 'Arial', sans-serif;
      }

      .nav {
        background-color: #121212;
        color: #eee;
      }

      ul.nav {
        list-style: none;
        background-color: #444;
        text-align: center;
        padding: 0;
        margin: 0;
      }
      .nav li {
        font-family: 'Oswald', sans-serif;
        font-size: 1.2em;
        line-height: 40px;
        height: 40px;
        display: inline-block;
        width: 120px;
      }

      .nav a {
        text-decoration: none;
        color: #fff;
        display: block;
        transition: .3s background-color;
      }

      .nav a:hover {
        background-color: #0C4B33;
      }

      .nav a.active {
        background-color: #fff;
        color: #444;
        cursor: default;
      }

      label {
        width: 130px;
        display: inline-block;
      }

      input, select {
        width: 280px;
      }

      .helptext {
        display: block;
        font-size: 0.8em;
        color: #999;
      }
      </p>
    </style>
  </head>
  <body>
    <div class="container">
      <ul class="nav">
        <li><a href="{% url 'client-list' %}">Clients</a></li>
        <li><a href="{% url 'entry-list' %}">Entries</a></li>
        <li><a href="{% url 'project-list' %}">Projects</a></li>
      </ul>
      {% block content %}{% endblock %}
    </div>
  </body>
</html>

timetracker/entries/templates/client_detail.html
{% extends "base.html" %}

{% block title %}Client projects{% endblock %}

{% block content %}
  <h2>Client projects</h2>

  <h3>Client</h3>
  {{ client.name }}

  <h3>Projects</h3>
  <ul>
    {% for project in client.project_set.all %}
    <li>
      {{ project.name }}
      <ul>
        {% for entry in project.entry_set.all %}
        <li>{{ entry.description }}</li>
        {% endfor %}
      </ul>
    </li>
    {% endfor %}
  </ul>
{% endblock %}

timetracker/entries/templates/clients.html
{% extends "base.html" %}

{% block title %}Clients{% endblock %}

{% block content %}
  <h2>Clients</h2>

  <form method="post">
    {% csrf_token %}
    {{ client_form.as_p }}
    <input type="submit" value="Create Client">
  </form>

  <ul>
    {% for client in client_list %}
    <li><a href="{% url 'client-detail' pk=client.pk %}">{{ client.name }}</a></li>
    {% endfor %}
  </ul>
{% endblock %}

timetracker/entries/templates/entries.html
{% extends "base.html" %}

{% block title %}Entries{% endblock %}

{% block content %}
  <h2>Entries</h2>
  <form method="post">
    {% csrf_token %}
    {{ entry_form.as_p }}
    <input type="submit" value="Create Entry">
  </form>

  <ul>
    {% for entry in entry_list %}
    <li>{{ entry.description }}</li>
    {% endfor %}
  </ul>
{% endblock %}

timetracker/entries/templates/projects.html
{% extends "base.html" %}

{% block title %}Projects{% endblock %}

{% block content %}
  <h2>Projects</h2>

  <form method="POST">
    {% csrf_token %}
    {{ project_form.as_p }}
    <input type="submit" value="Create Project">
  </form>

  <ul>
    {% for project in project_list %}
    <li>{{ project.name }} (<a href="{% url 'client-detail' pk=project.client.pk %}">{{ project.client.name }}</a>)</li>
    {% endfor %}
  </ul>
{% endblock %}